language: python

sudo: false

env:
  - DJANGO_PACKAGE=Django==1.8.18
  - DJANGO_PACKAGE=Django==1.9.13
  - DJANGO_PACKAGE=Django==1.10.7
  - DJANGO_PACKAGE=Django==1.11.5
install:
  - pip install -r tests/requirements.txt
  - python setup.py install

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-django18
    python: 2.7
  - env: TOX_ENV=py27-django19
    python: 2.7
  - env: TOX_ENV=py27-django110
    python: 2.7
  - env: TOX_ENV=py27-django111
    python: 2.7
  - env: TOX_ENV=py35-django20
    python: 3.5
  - env: TOX_ENV=py36-django111
    python: 3.6
  - env: TOX_ENV=py36-django20
    python: 3.6
  - env: TOX_ENV=py36-django21
    python: 3.6
  - env: TOX_ENV=py36-django22
    python: 3.6
  - env: TOX_ENV=py37-django20
    python: 3.7
  - env: TOX_ENV=py37-django21
    python: 3.7
  - env: TOX_ENV=py37-django22
    python: 3.7

script: travis_retry tox -e $TOX_ENV